// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZU4s4O6kePszZC3kv8xsbqnQfOgPv38o',
    appId: '1:773809522874:web:a3c9a7ff44910e06c05a83',
    messagingSenderId: '773809522874',
    projectId: 'shoply-ecommerce-app',
    authDomain: 'shoply-ecommerce-app.firebaseapp.com',
    storageBucket: 'shoply-ecommerce-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6-jFwNmd4KHPuWiTyBrJtItM_WnYhNts',
    appId: '1:773809522874:android:e2315ca856ca6c92c05a83',
    messagingSenderId: '773809522874',
    projectId: 'shoply-ecommerce-app',
    storageBucket: 'shoply-ecommerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIEbYJSwW2sFzXkKQzZOJTPGmHpdJ1cq4',
    appId: '1:773809522874:ios:ed66a764f55c446fc05a83',
    messagingSenderId: '773809522874',
    projectId: 'shoply-ecommerce-app',
    storageBucket: 'shoply-ecommerce-app.firebasestorage.app',
    iosBundleId: 'com.example.shoply',
  );
}
